<?php
$stateArray = array(
	'Mississippi',
	'Alabama',
	'Louisiana',
	'South Carolina',
	'Utah',
	'Tennessee',
	'Arkansas',
	'North Carolina',
	'Georgia',
	'Texas',
	'North Dakota',
	'Oklahoma',
	'Kentucky',
	'South Dakota',
	'Kansas',
	'Iowa',
	'Nebraska',
	'Indiana',
	'Minnesota',
	'Missouri',
	'Virginia',
	'New Mexico',
	'Illinois',
	'Pennsylvania',
	'West Virginia',
	'Idaho',
	'Ohio',
	'Florida',
	'Maryland',
	'Michigan',
	'Wisconsin',
	'Arizona',
	'Delaware',
	'New Jersey',
	'District of Columbia',
	'Montana',
	'California',
	'Colorado',
	'New York',
	'Wyoming',
	'Connecticut',
	'Rhode Island',
	'Washington',
	'Alaska',
	'Hawaii',
	'Oregon',
	'Nevada',
	'Massachusetts',
	'Maine',
	'New Hampshire',
	'Vermont'
);

?>