<!-- Template to display list of Categories -->

<table cellpadding=5 cellspacing=0 bgcolor=c9c9c9 width=95% align=center>
<tr>	
	<TD class=header><a href="{SORT_LINK}&orderColumn=title&titleOrder={TITLE_ORDER}" class=header>Title</a></td>
	<TD class=header><a href="{SORT_LINK}&orderColumn=sortOrder&sortOrderOrder={SORT_ORDER_ORDER}" class=header>Sort Order</td>
	<TD class=header>Remove From ShowMe Display</td>	
</tr>
{OFFER_LIST}